import tmrm = require('azure-pipelines-task-lib/mock-run')
import path = require('path')
import mockFetch = require('../../tests/mockFetch')
import { mockAzureClient } from '../../tests/mockAzureClient'

const taskPath = path.join(__dirname, '..', 'main.js')
const tmr: tmrm.TaskMockRunner = new tmrm.TaskMockRunner(taskPath)

tmr.setVariableName('Build.BuildId', '1')
tmr.setVariableName('Build.SourceVersion', '1')

tmr.setInput('serviceConnection', 'ID1')
tmr.setInput('targetApplicationId', '1')
tmr.setInput('versionName', 'ECOM-11.2')
tmr.setInput('versionDescription', 'Generated by Azure')
// force to wrong format to mimic azure bug which convert date when returned by getInput
tmr.setInput('versionStartDate', '01/24/2023 12:10:00')
// force to wrong format to mimic azure bug which convert date when returned by getInput
tmr.setInput('versionReleaseDate', '11/02/2023 09:30:00')
tmr.setInput('versionReleased', 'true')
tmr.setInput('autoCreateVersion', 'true')
tmr.setInput('scopeIssueKeys', 'TEM-10,TEM-100')
tmr.setInput('scopeJql', `project = "ECP" and key in (ECP-288, ECP-287)`)
tmr.setInput('sendNotification', 'true')

tmr.registerMock('./AzureClient', mockAzureClient())
tmr.registerMock('node-fetch', mockFetch())

tmr.run()
