name: NodeJS with Webpack

on:
  pull_request:
  push:
    branches:
      - "!master"
      - "!patch/**"

jobs:
  build:
    name: Build azure extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      name: Use Node.js 20.x
      with:
        node-version: 20
    - name: Build
      env:
        BUILD_ENV: development
      run: |
        npm install
        TZ="Europe/Zurich" npm run build
