name: NodeJS with Webpack

env:
  ADO_PAT: ${{ secrets.AZURE_CI_AOD_PAT }}
  BUILD_ENV: development
  ADO_ACCOUNT_URI: https://dev.azure.com/julien0711
  DEV_PUBLISHER: JulienPublisher

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run dev
